apiVersion: v1
kind: Pod
metadata:
  name: hongao-develop
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
              - key: nvidia.com/cuda.runtime.major
                operator: In
                values:
                  - "13"
  containers:
    - name: debug-container
      image: condaforge/mambaforge
      command:
      - /bin/bash
      - -c
      args:
      - |
        apt-get update && apt-get install -y git openssh-client zip && rm -rf /var/lib/apt/lists/* && \
        mkdir -p /root/.ssh && \
        echo "$ID_RSA" > /root/.ssh/id_rsa && \
        chmod 600 /root/.ssh/id_rsa && \
        ssh-keyscan github.com >> /root/.ssh/known_hosts && \
        git clone git@github.com:Hongao0611/LIGN211-Phonology.git /app/code && \
        pip install numpy torch scikit-learn && \
        echo "Ready for development:)" && \
        cd /app/code && \
        python script/classifier2.py --output /mnt/pvc/classifier-baseline.json > /mnt/pvc/classifier-baseline.log 2>&1 && \
        python script/classifier2.py --seg-vectors vectors/GloVe_24.txt --output /mnt/pvc/classifier-GloVe24.json > /mnt/pvc/classifier-GloVe24.log 2>&1 && \
        python script/classifier2.py --seg-vectors vectors/GloVe.txt --output /mnt/pvc/classifier-GloVe.json > /mnt/pvc/classifier-GloVe.log 2>&1 && \
        echo "Success!"
      env:
      - name: ID_RSA
        valueFrom:
          secretKeyRef:
            name: hongao-secret
            key: id_rsa
      volumeMounts:
        - mountPath: /app/code
          name: storage-volume
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /mnt/pvc
          name: pvc-volume
      resources:
        requests:
          nvidia.com/gpu: "1"
          cpu: "4"
          memory: "32Gi"
        limits:
          nvidia.com/gpu: "1"
          cpu: "4"
          memory: "32Gi"
  volumes:
    - name: storage-volume
      emptyDir:
        medium: Memory
        sizeLimit: 100Gi
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: hongao-storage
  restartPolicy: Never